//
// Created by PANG TAO on 4/7/21.
//

#ifndef CONTACT_TRAJECTORY_OPTIMIZATION_SRC_TRAJ_OPT_PLAN_BASE_H_
#define CONTACT_TRAJECTORY_OPTIMIZATION_SRC_TRAJ_OPT_PLAN_BASE_H_

class plan_base {

};

#endif //CONTACT_TRAJECTORY_OPTIMIZATION_SRC_TRAJ_OPT_PLAN_BASE_H_
