# Communication Parameters
lcm_status_channel: "IIWA_STATUS"
lcm_command_channel: "IIWA_COMMAND"
lcm_plan_channel: "ROBOT_PLAN"
zmq_socket_plan: "5555"
zmq_socket_abort: "5556"
zmq_socket_status: "5557"  # pub-sub for feedback status and result.
status_channel_name: "PLAN_STATUS"
staus_update_period_seconds: 0.01

# Robot Parameters
robot_sdf_path: "drake/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf"
robot_baselink_name: "iiwa_link_0"
robot_ee_body_name: "iiwa_link_7"
robot_nominal_joint: [0.165, 1.22, 0.781, -1.41, 0.415, -1.3, -0.75]

# Control Parameters
control_period: 0.005
q_threshold: 0.05 # norm between current q and commanded q.

# Print Parameters.
print_period_seconds: 10.
