# Communication Parameters
lcm_status_channel: "IIWA_STATUS"
lcm_command_channel: "IIWA_COMMAND"
lcm_plan_channel: "ROBOT_PLAN"
zmq_socket: "tcp://*:5555"

# Robot Parameters
robot_sdf_path: "drake/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf"
robot_baselink_name: "iiwa_link_0"
robot_ee_body_name: "iiwa_link_5"

# Control Parameters
control_period: 0.005
q_threshold: 0.05 # norm between current q and commanded q.
