name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 6 * * *"  # 6am everyday.

jobs:
  bionic:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        run: sudo ./scripts/install_dependencies.sh
        shell: bash
      - name: build_and_test
        run: sudo ./scripts/build_and_run_tests.sh
