name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 6 * * *"  # 6am everyday.

jobs:
  bionic:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: build and test action step
        uses: ./ # Uses an action in the root directory
        id: build_test
